### ISSUE TITLE
Utilisation de deque sans explications

### ISSUE THREAD

**Issue by boopr** [ArnaudCalmettes/article-async#1]
Salut,
Bravo pour ton tutoriel, c'est exactement ce dont on a besoin. Par contre, dans la partie une, tu utilises `deque()` depuis le module `collection` sans explications. Et si je me place dans la peau du débutant, il ne va pas savoir ce que c'est (d'ailleurs, je ne le sais pas non plus :smile: ).

**Comment by ArnaudCalmettes** [comment]
OK, je vais lâcher une ou deux explications pour expliquer ce qu'est une `deque` et pourquoi j'en utilise une plutôt qu'une liste.

**Comment by ArnaudCalmettes** [comment]
Ça te va, comme ça, ou c'est encore obscur ?

https://github.com/ArnaudCalmettes/article-async/commit/b816be16dd0d50633edc156db0cff082799fd486

**Comment by boopr** [comment]
Ouep! Ça me semble nickel !
