### ISSUE TITLE
Génération PDF

### ISSUE THREAD

**Issue by Vayel** [ArnaudCalmettes/article-async#2]
Y aurait-il moyen d'avoir un rendu PDF, histoire qu'un étudiant dont la ligne Internet n'est pas encore activée puisse relire tout ça ? ^^

**Comment by ArnaudCalmettes** [comment]
Je vais rajouter la branche gh-pages

**Comment by ArnaudCalmettes** [comment]
http://arnaudcalmettes.github.io/article-async/async.pdf

**Comment by Vayel** [comment]
Thanks.
